#! /bin/bash

# Unlike the other files, this is a bash script that should be executed.

usage() {
    cat<<EOF
Synopsis: choose-storm /path/to/message-files/message /path/to/merged-by-field 2025-07-19_18:00:00 [ "NNL" [ 24 ] ]

Arguments:
  /path/to/message-files/message = Required. Prefix to prepend to message number. This must be the directory, followed by /message. Hence, appending 3 gives message 3's file
  /path/to/merged-by-field = Required. the location of the "merged-by-field" directory generated by grabNpost.sh
  2025-07-19_18:00:00 = Required. date and time of beginning of your forecast. Used to eliminate old messages.
  NNL = Optional. preferred storm (eg. 93L or 18L) or 00X for no preference. Script will use this storm if data is present. Default: no preference; 00x
  24 = Optional. Maximum age of a message in hours before it is discarded. Default: 24

On success, script exits 0 after printing to stdout:
  CHOSEN MESSAGE message3 FILES 03l.2027190818.hfsa.VARNAME.grb2
or, if no storms are found:
  CHOSEN GFS FILES 00x.2027190818.gfso.VARNAME.grb2

On failure, script exits with non-zero exit status. Read the stderr stream for an explanation of the error. Reason for exit will be near the end.
EOF
}

if [[ "$#" -lt 3 ]] ; then
    usage 1>&2
    echo SCRIPT IS EXITING DUE TO MISSING ARGUMENTS. SEE USAGE. 1>&2
    exit 1
fi

storm_messages="$1"
merged_by_field="$2"
YYYY_MM_DD_HH_00_00="$3"
preferred_storm="${4:-999}"
preferred_storm=$( echo "$preferred_storm" | tr a-z A-Z )

# Maximum age of a storm message before discarding it.
max_age_in_hours=24
max_age_in_hours="${5:-$max_age_in_hours}"
max_age_in_seconds=$(( 3600 * max_age_in_hours ))

YYYY="${YYYY_MM_DD_HH_00_00:0:4}"
MM="${YYYY_MM_DD_HH_00_00:5:2}"
DD="${YYYY_MM_DD_HH_00_00:8:2}"
HH="${YYYY_MM_DD_HH_00_00:11:2}"

epoch_time=$( date --date="${YYYY}-${MM}-${DD}t${HH}:00:00" +%s )

check_for_storm_data() {
    local id=$( echo "$1" | tr A-Z a-z ) # 00x, 03l, 91w, etc.
    local model=$( echo "$2" | tr A-Z a-z ) # gfso or hfsa

    for field in UVGRD SFC TMP SPFH HGT DZDT CLMR RWMR ICMR SNMR ; do
        local filename="$merged_by_field/$id.$YYYY$MM$DD$HH.$model.$field.grb2"
        if [[ ! -s "$filename" ]] ; then
            echo "$id $YYYY discarded due to missing $filename" 1>&2
            return 1
        fi
    done
    return 0
}

scan_messages_for() {
    chosen_message=0 # Note: not local. This is the way the value is returned to the caller.
    chosen_storm="none" # Also a return value

    local model=$( echo "${1:-hfsa}" | tr A-Z a-z )
    local basin="${2:-x}" # a, e, etc.
    local id="${3:-00x}" # 03L, 91W, etc.
    local north_only=$( echo "${4:-NO}" | tr a-z A-Z ) # YES = only positive latitude

    id=$( echo "$id" | tr a-z A-Z ) # id must be upper-case

    BASIN_UC=$( echo "${basin:0:1}" | tr a-z A-Z ) # upper-case basin
    basin_lc=$( echo "${basin:0:1}" | tr A-Z a-z ) # lower-case basin

    local message_number
    for message_number in $( seq 1 7 ) ; do
        local messageN="message$message_number"
        local message_file="$storm_messages$message_number"
        if ! [[ -s "$message_file" ]] ; then
            echo "ERROR: $messageN not found; file empty or missing: $message_file" 1>&2
            continue
        fi

        local contents=$( head -1 "$message_file" )

        # Relevant contents are below. Note that all letters are capitalized. Character indices are below contents
        #
        # NHC  96E INVEST    250707 1200 178N 1125W
        # 00000000001111111111222222222233333333334
        # 01234567890123456789012345678901234567890

        message_id="${contents:5:3}" # 03L, 91W, etc.
        local message_id_lc=$( echo "$message_id" | tr A-Z a-z )
        message_BASIN_UC="${contents:7:1}"
        message_YYYY="20${contents:19:2}"
        message_MM="${contents:21:2}"
        message_DD="${contents:23:2}"
        message_HH="${contents:26:2}"
        message_NorthSouth="${contents:34:1}"
        message_posix_time="${message_YYYY}-${message_MM}-${message_DD}t${message_HH}:00:00"
        message_epoch_time=$( date --date="${message_posix_time}" +%s )
        message_age=$(( epoch_time - message_epoch_time ))

        if (( message_age > max_age_in_seconds )) ; then
            echo "${messageN}: Skipping old $message_id message from ${message_posix_time} (age $(( message_age / 3600)) hours > $((max_age_in_seconds / 3600 )))" 1>&2
            continue
        fi

        if [[ "$id" != "00X" && "$message_id" != "$id" ]] ; then
            echo "${messageN}: Skipping message for wrong storm; is $message_id not $id" 1>&2
            continue
        fi

        if [[ "$BASIN_UC" != "X" && "$BASIN_UC" != "$message_BASIN_UC" ]] ; then
            echo "${messageN}: Skipping message for wrong basin; is $message_BASIN_UC not $BASIN_UC" 1>&2
            continue
        fi

        if [[ "$north_only" == "YES" && "$message_NorthSouth" != "N" ]] ; then
            echo "${messageN}: Skipping message with wrong latitude; is $message_NorthSouth, not N" 1>&2
            continue
        fi

        message_id_lc=$( echo "$message_id" | tr A-Z a-z )
        if ( ! check_for_storm_data "$message_id" "$model" ) ; then
            echo "${messageN}: Skipping message for storm with no data available." 1>&2
            continue
        fi

        echo "${messageN}: Matches search parameters." 1>&2
        
        chosen_message=$message_number
        chosen_storm="$message_id_lc.$YYYY$MM$DD$HH.hfsa.VARNAME.grb2"
        return 0
    done

    echo "No match." 1>&2
    return 0
}

scan_messages() {
    if [[ "$preferred_storm" != 999 ]] ; then
        echo "Searching for preferred storm $preferred_storm with data present..." 1>&2
        scan_messages_for hfsa x "$preferred_storm" NO
        if (( chosen_message > 0 )) ; then
            echo "Match found for preferred storm. Engaging manual override." 1>&2
            echo "CHOSEN MESSAGE message${chosen_message} FILES $chosen_storm" 1>&2
            echo "CHOSEN MESSAGE message${chosen_message} FILES $chosen_storm"
            return 0
        else
            echo "Could not use preferred storm $preferred_storm. Manual override canceled." 1>&2
        fi
    fi

    echo "Searching for the highest-priority North Atlantic storm with data present..." 1>&2
    scan_messages_for hfsa a 00x YES 1>&2
    if (( chosen_message > 0 )) ; then
        echo "Match found in North Atlantic." 1>&2
        echo "CHOSEN MESSAGE message${chosen_message} FILES $chosen_storm" 1>&2
        echo "CHOSEN MESSAGE message${chosen_message} FILES $chosen_storm"
        return 0
    else
        echo "Found no storms in the North Atlantic with data present." 1>&2
    fi

    # Failing that, pick any storm
    echo "Searching for the highest-priority storm with data present..." 1>&2
    scan_messages_for hfsa x 00x NO 1>&2
    if (( chosen_message > 0 )) ; then
        echo "Match found for a message of unrestricted location." 1>&2
        echo "CHOSEN MESSAGE message${chosen_message} FILES $chosen_storm" 1>&2
        echo "CHOSEN MESSAGE message${chosen_message} FILES $chosen_storm"
        return 0
    fi

    # Fallback: use GFS
    echo "No available storms. Checking for gfs-only data..." 1>&2
    if ( check_for_storm_data 00x gfso ) ; then
        echo "GFS grb2 files are present. All messages were rejected. Using only GFS." 1>&2
        chosen_storm=$( echo "00x.$YYYY$MM$DD$HH.gfso.VARNAME.grb2" | tr A-Z a-z )
        echo "CHOSEN MESSAGE gfs FILES $chosen_storm" 1>&2
        echo "CHOSEN MESSAGE gfs FILES $chosen_storm"
        return 0
    fi

    echo "ERROR: No data available for time ${YYYY_MM_DD_HH_00_00}" 1>&2
    echo "ERROR: No data available for time ${YYYY_MM_DD_HH_00_00}"
    echo "SCRIPT IS EXITING BECAUSE IT COULD FIND NO AVAILABLE DATA" 1>&2
    exit 1
}

scan_messages
